swagger: '2.0'
info:
 title: mytest2-api 
 description: Sample API on API Gateway with a Google Cloud Functions backend
 version: 1.0.0
schemes:
 - https
produces:
 - application/json
paths:
 /helloHttp:
  get:
   summary: This is a test api
   operationId: helloHttp
   x-google-backend:
    address: https://us-central1-bullitt-customer-portal.cloudfunctions.net/test-function
   responses:
    '200':
      description: A successful response
      schema:
       type: string